package com.bleachlizard.thesiscore.instability;

import com.bleachlizard.thesiscore.knowledge.InterpretationResult;
import com.bleachlizard.thesiscore.registry.ThesisCoreAttachments;
import net.minecraft.world.entity.player.Player;

/**
 * Stateless logic for the instability system.
 *
 * <p>Instability is generated by every magical action and is amplified by poor
 * interpretation. It accumulates in {@link PlayerInstability} and determines
 * the {@link InstabilityOutcome} experienced by the player.
 *
 * <h2>How outcomes are resolved</h2>
 * <p>Two inputs combine to produce an outcome:
 * <ol>
 *   <li>The player's normalized instability (0.0–1.0)</li>
 *   <li>A severity offset derived from the {@link InterpretationResult}</li>
 * </ol>
 * <p>These are summed into a {@code pressure} value (0.0–2.0) which is then
 * mapped to an {@link InstabilityOutcome}. High instability players get worse
 * outcomes even from correct interpretations; low instability players can
 * survive imperfect interpretations relatively cleanly.
 *
 * <h2>XP stabilization</h2>
 * <p>Players can spend XP to reduce instability. Each XP level converts to a
 * fixed instability reduction. Pre-cast stabilization can be applied before
 * an action; reactive stabilization is more wasteful.
 */
public final class InstabilitySystem {

    // -------------------------------------------------------------------------
    // Instability gain multipliers per InterpretationResult
    // -------------------------------------------------------------------------

    /** No gain for correct interpretation — clean use of magic produces no instability. */
    private static final float GAIN_CORRECT = 0f;
    /** Minor gain for partial — the player understood most but not all. */
    private static final float GAIN_PARTIAL = 0.5f;
    /** Above-average gain for incorrect — wrong but confident, danger they don't see. */
    private static final float GAIN_INCORRECT = 1.5f;
    /** Small gain for failure — not much happened, so not much went wrong. */
    private static final float GAIN_FAILURE = 0.25f;
    /** Largest gain for catastrophic — deeply wrong and deeply confident. */
    private static final float GAIN_CATASTROPHIC = 3.0f;

    // -------------------------------------------------------------------------
    // Pressure offsets for outcome resolution
    // -------------------------------------------------------------------------

    private static final float OFFSET_CORRECT = 0f;
    private static final float OFFSET_PARTIAL = 0.1f;
    private static final float OFFSET_INCORRECT = 0.35f;
    private static final float OFFSET_FAILURE = 0.2f;
    private static final float OFFSET_CATASTROPHIC = 0.6f;

    // -------------------------------------------------------------------------
    // Pressure → outcome thresholds (normalized pressure 0.0–1.0+)
    // -------------------------------------------------------------------------

    private static final float THRESHOLD_PERFECT    = 0.2f;
    private static final float THRESHOLD_IMPERFECT  = 0.4f;
    private static final float THRESHOLD_UNSTABLE   = 0.6f;
    private static final float THRESHOLD_FAILURE    = 0.8f;
    // >= 0.8 → CATASTROPHIC

    // -------------------------------------------------------------------------
    // XP stabilization constants
    // -------------------------------------------------------------------------

    /** Instability reduced per XP level burned during pre-cast stabilization. */
    public static final float INSTABILITY_PER_XP_LEVEL_PRECAST = 4f;
    /** Instability reduced per XP level burned during reactive stabilization (less efficient). */
    public static final float INSTABILITY_PER_XP_LEVEL_REACTIVE = 2.5f;

    // -------------------------------------------------------------------------
    // Core API
    // -------------------------------------------------------------------------

    /**
     * Calculates how much instability a magical action generates.
     *
     * @param result      the interpretation quality for the action
     * @param actionPower the relative magnitude of the action (1.0 = baseline)
     * @return raw instability to add to {@link PlayerInstability}
     */
    public static float calculateGain(InterpretationResult result, float actionPower) {
        float multiplier = switch (result) {
            case CORRECT            -> GAIN_CORRECT;
            case PARTIAL            -> GAIN_PARTIAL;
            case INCORRECT          -> GAIN_INCORRECT;
            case FAILURE            -> GAIN_FAILURE;
            case CATASTROPHIC_FAILURE -> GAIN_CATASTROPHIC;
        };
        return multiplier * Math.max(0f, actionPower);
    }

    /**
     * Resolves the {@link InstabilityOutcome} of a magical action.
     *
     * <p>The outcome is determined by combining the player's current instability
     * with a severity offset from the interpretation result. Higher instability
     * and worse interpretations push outcomes toward {@link InstabilityOutcome#CATASTROPHIC}.
     *
     * @param instability the player's current instability state
     * @param result      the interpretation result from {@link com.bleachlizard.thesiscore.knowledge.PlayerKnowledgeState#evaluate}
     * @return the outcome the player experiences
     */
    public static InstabilityOutcome resolveOutcome(PlayerInstability instability, InterpretationResult result) {
        float normalizedInstability = instability.getNormalized();
        float offset = switch (result) {
            case CORRECT            -> OFFSET_CORRECT;
            case PARTIAL            -> OFFSET_PARTIAL;
            case INCORRECT          -> OFFSET_INCORRECT;
            case FAILURE            -> OFFSET_FAILURE;
            case CATASTROPHIC_FAILURE -> OFFSET_CATASTROPHIC;
        };

        float pressure = Math.clamp(normalizedInstability + offset, 0f, 1f);

        if (pressure < THRESHOLD_PERFECT)   return InstabilityOutcome.PERFECT;
        if (pressure < THRESHOLD_IMPERFECT) return InstabilityOutcome.IMPERFECT;
        if (pressure < THRESHOLD_UNSTABLE)  return InstabilityOutcome.UNSTABLE;
        if (pressure < THRESHOLD_FAILURE)   return InstabilityOutcome.FAILURE;
        return InstabilityOutcome.CATASTROPHIC;
    }

    /**
     * Applies a magical action to a player: calculates gain, adds it to their
     * instability, and returns the resulting outcome. Convenience method that
     * wraps {@link #calculateGain} and {@link #resolveOutcome}.
     */
    public static InstabilityOutcome applyAction(
            Player player, InterpretationResult result, float actionPower) {
        PlayerInstability state = player.getData(ThesisCoreAttachments.PLAYER_INSTABILITY);
        InstabilityOutcome outcome = resolveOutcome(state, result);
        state.add(calculateGain(result, actionPower));
        return outcome;
    }

    /**
     * Spends XP levels to reduce instability before an action (pre-cast stabilization).
     * More efficient than reactive stabilization.
     *
     * @param player    the player spending XP
     * @param xpLevels  the number of XP levels to burn
     */
    public static void stabilizePrecast(Player player, int xpLevels) {
        if (xpLevels <= 0) return;
        int available = Math.min(xpLevels, player.experienceLevel);
        player.giveExperienceLevels(-available);
        player.getData(ThesisCoreAttachments.PLAYER_INSTABILITY)
                .reduce(available * INSTABILITY_PER_XP_LEVEL_PRECAST);
    }

    /**
     * Spends XP reactively to mitigate instability after a bad result.
     * Less efficient than pre-cast stabilization; represents panicked intervention.
     *
     * @param player    the player spending XP
     * @param xpLevels  the number of XP levels to burn
     */
    public static void stabilizeReactive(Player player, int xpLevels) {
        if (xpLevels <= 0) return;
        int available = Math.min(xpLevels, player.experienceLevel);
        player.giveExperienceLevels(-available);
        player.getData(ThesisCoreAttachments.PLAYER_INSTABILITY)
                .reduce(available * INSTABILITY_PER_XP_LEVEL_REACTIVE);
    }

    private InstabilitySystem() {}
}
